"""Adapter that renders a HyperFrames composition (HTML) to a video clip.

The render invocation is read from ``engine/engine.json`` so there is exactly one
place to adjust for your installed HyperFrames version. Nothing here hand-edits a
composition — compositions are generated by ``engine/composition.py`` from the plan.

Usage is intentionally small: ``render(html_path, out_path, fps, width, height)``.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from typing import Optional

_ENGINE_JSON = Path(__file__).with_name("engine.json")


def _cfg() -> dict:
    return json.loads(_ENGINE_JSON.read_text())


def available() -> bool:
    """True if npx (Node) is on PATH. HyperFrames itself is invoked via npx."""
    return shutil.which("npx") is not None


def build_render_command(html_path: Path, out_path: Path, fps: float, width: int, height: int) -> list[str]:
    cfg = _cfg()["render"]
    cmd = list(cfg["command"])
    cmd += [cfg["input_flag"], str(html_path), cfg["output_flag"], str(out_path)]
    for arg in cfg.get("extra_args", []):
        cmd.append(arg.replace("{fps}", str(int(round(fps)))).replace("{width}", str(width)).replace("{height}", str(height)))
    return cmd


def render(
    html_path: Path,
    out_path: Path,
    fps: float,
    width: int,
    height: int,
    dry_run: bool = False,
) -> Optional[Path]:
    """Render one composition. Returns the output path, or None on dry-run."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = build_render_command(html_path, out_path, fps, width, height)
    printable = " ".join(cmd)
    if dry_run:
        print(f"[dry-run] {printable}")
        return None
    if not available():
        raise RuntimeError(
            "Node/npx not found — HyperFrames requires Node 22+. Run scripts/doctor.sh."
        )
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"HyperFrames render failed:\n{printable}\n{proc.stderr[-2000:]}")
    return out_path
